name: "tagged-release"

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      # ...
      - uses: actions/checkout@v2
      - name: "Build & test"
        run: |
          echo "done!"
      - name: Get Latest Release
        id: release_version
        uses: pozetroninc/github-action-get-latest-release@v0.5.0
        with:
          repository: ${{ github.repository }} 
          excludes: prerelease, draft
      - name: "Echo output"
        run: |
          echo "release ${{ steps.release_version.outputs.release }}"
      - name: Deploy to production env on Heroku
        run: ./deploy.sh ${{ steps.release_version.outputs.release }} dusanmilunovic17@gmail.com ${{secrets.HEROKU_API_KEY_PROD}} prod-agent-backend-postgres ${{secrets.SQL_PASSWORD_PROD}} ${{secrets.FLASK_SECRET_KEY}} aoptzkmb aoptzkmb prod
